DROP TABLE IF EXISTS ANIMALDIMENSION;
CREATE TABLE ANIMALDIMENSION(
   ANIMAL_DIM_KEY SERIAL PRIMARY KEY,
   ANIMAL_ID VARCHAR,
   ANIMAL_TYPE VARCHAR,
   ANIMAL_NAME VARCHAR,
   DOB DATE,
   BREED VARCHAR,
   COLOR VARCHAR,
   REPROD VARCHAR,
   GENDER VARCHAR,
   TIMESTMP TIMESTAMP
);

DROP TABLE IF EXISTS TIMINGDIMENSION;
CREATE TABLE TIMINGDIMENSION(
   TIME_DIM_KEY SERIAL PRIMARY KEY,
   MONTHH VARCHAR,
   YEARR INT
);

DROP TABLE IF EXISTS OUTCOMEDIMENSION;
CREATE TABLE OUTCOMEDIMENSION(
   OUTCOME_DIM_KEY SERIAL PRIMARY KEY,
   OUTCOME_TYPE VARCHAR,
   OUTCOME_SUBTYPE VARCHAR
);

DROP TABLE IF EXISTS OUTCOMESFACT;
CREATE TABLE OUTCOMESFACT(
   OUTCOMESFACT_KEY SERIAL PRIMARY KEY,
   OUTCOME_DIM_KEY INT REFERENCES OUTCOMEDIMENSION(OUTCOME_DIM_KEY),
   ANIMAL_DIM_KEY INT REFERENCES ANIMALDIMENSION(ANIMAL_DIM_KEY),
   TIME_DIM_KEY INT REFERENCES TIMINGDIMENSION(TIME_DIM_KEY)
);

DROP TABLE IF EXISTS TEMP_TABLE;
CREATE TABLE TEMP_TABLE(
   TEMP_KEY SERIAL PRIMARY KEY,
   ANIMAL_ID VARCHAR,
   ANIMAL_TYPE VARCHAR,
   ANIMAL_NAME VARCHAR,
   DOB DATE,
   BREED VARCHAR,
   COLOR VARCHAR,
   REPROD VARCHAR,
   GENDER VARCHAR,
   TIMESTMP TIMESTAMP,
   MONTHH VARCHAR,
   YEARR INT,
   OUTCOME_TYPE VARCHAR,
   OUTCOME_SUBTYPE VARCHAR
);